server:
  port: 8787
spring:
  application:
    name: spring-redis-app
  datasource:
    username: sa
    password: password
    url: jdbc:h2:file:~/sample/redis_test
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

